// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1721305547);
user_pref("app.update.lastUpdateTime.region-update-timer", 1721305547);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1721305547);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1721305577);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1721305547);
user_pref("browser.crashReports.unsubmittedCheck.autoSubmit2", true);
user_pref("browser.region.update.updated", 1721305494);
user_pref("browser.search.region", "US");
user_pref("calendar.caldav.googleResync", 1721305493);
user_pref("calendar.list.sortOrder", "59a78f8e-a89e-4f26-a632-cac29d2ae17e");
user_pref("calendar.registry.59a78f8e-a89e-4f26-a632-cac29d2ae17e.calendar-main-default", true);
user_pref("calendar.registry.59a78f8e-a89e-4f26-a632-cac29d2ae17e.calendar-main-in-composite", true);
user_pref("calendar.registry.59a78f8e-a89e-4f26-a632-cac29d2ae17e.disabled", true);
user_pref("calendar.registry.59a78f8e-a89e-4f26-a632-cac29d2ae17e.name", "Home");
user_pref("calendar.registry.59a78f8e-a89e-4f26-a632-cac29d2ae17e.type", "storage");
user_pref("calendar.registry.59a78f8e-a89e-4f26-a632-cac29d2ae17e.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "America/Denver");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1721305527188");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1721305547);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20240614163201");
user_pref("extensions.lastAppVersion", "115.12.0");
user_pref("extensions.lastPlatformVersion", "115.12.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.extension.hidden", false);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", false);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.external-editor-revived@tsundere.moe", true);
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"06dfa671-3ec7-4591-a137-a2a5215944a3\",\"google@search.mozilla.org\":\"88919a21-210e-4004-a8a3-831d8913d7ae\",\"ddg@search.mozilla.org\":\"050944fe-ff7b-4689-b4d4-8d0985f7bc28\",\"amazondotcom@search.mozilla.org\":\"4dd2840e-ce81-4e87-a17a-f27d277d1163\",\"wikipedia@search.mozilla.org\":\"42fcf226-4953-4da6-8d19-23dacd66dcf6\",\"bing@search.mozilla.org\":\"6119354b-412f-4ede-a9a2-8465e8994dc4\",\"external-editor-revived@tsundere.moe\":\"d9f1ad79-a066-4c68-8340-065e0627a5f1\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("idle.lastDailyNotification", 1721307095);
user_pref("ldap_2.servers.history.uid", "c76bb523-6da1-44a4-adf3-2c1b27bbcc1a");
user_pref("ldap_2.servers.pab.uid", "783a5b2d-0dd4-47f3-a8b9-368edbe64d07");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.account.account1.server", "server1");
user_pref("mail.account.account4.server", "server2");
user_pref("mail.account.lastKey", 4);
user_pref("mail.accountmanager.accounts", "account1,account4");
user_pref("mail.biff.play_sound", false);
user_pref("mail.biff.show_alert", false);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.server.server1.check_new_mail", true);
user_pref("mail.server.server1.check_time", 1);
user_pref("mail.server.server1.directory", "/home/crumb/.thunderbird/pgte5db0.default-release/Mail/Feeds");
user_pref("mail.server.server1.directory-rel", "[ProfD]Mail/Feeds");
user_pref("mail.server.server1.feed_options", "{\"version\":2,\"updates\":{\"enabled\":true,\"updateMinutes\":100,\"updateUnits\":\"min\",\"lastUpdateTime\":null,\"lastDownloadTime\":null,\"updatePeriod\":null,\"updateFrequency\":1,\"updateBase\":null},\"category\":{\"enabled\":false,\"prefixEnabled\":false,\"prefix\":null}}");
user_pref("mail.server.server1.hostname", "Feeds");
user_pref("mail.server.server1.lastFilterTime", 28688527);
user_pref("mail.server.server1.name", "cool fee");
user_pref("mail.server.server1.nextFilterTime", 28688537);
user_pref("mail.server.server1.spamActionTargetAccount", "mailbox://nobody@Feeds");
user_pref("mail.server.server1.storeContractID", "@mozilla.org/msgstore/berkeleystore;1");
user_pref("mail.server.server1.type", "rss");
user_pref("mail.server.server1.userName", "nobody");
user_pref("mail.server.server2.hostname", "prpl-irc");
user_pref("mail.server.server2.imAccount", "account1");
user_pref("mail.server.server2.storeContractID", "@mozilla.org/msgstore/berkeleystore;1");
user_pref("mail.server.server2.type", "im");
user_pref("mail.server.server2.userName", "MadeleineSydney@irc.libera.chat");
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 40);
user_pref("mailnews.database.global.datastore.id", "658c6928-02f7-4b28-a2b9-9ae2c3d2066");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "115.12.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("messenger.account.account1.autoJoin", "#fennel,haskell,guix");
user_pref("messenger.account.account1.autoLogin", true);
user_pref("messenger.account.account1.name", "MadeleineSydney@irc.libera.chat");
user_pref("messenger.account.account1.prpl", "prpl-irc");
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1721307095);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("rss.max_concurrent_feeds", 25);
user_pref("services.settings.clock_skew_seconds", -12596);
user_pref("services.settings.last_etag", "\"1648185887941\"");
user_pref("services.settings.last_update_seconds", 1721318151);
user_pref("services.settings.thunderbird.hijack-blocklists.last_check", 1721318151);
user_pref("services.settings.thunderbird.search-config.last_check", 1721318151);
user_pref("services.settings.thunderbird.url-classifier-skip-urls.last_check", 1721318151);
user_pref("spellchecker.dictionary", "en-US,en-GB");
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1721307095);
user_pref("toolkit.startup.last_success", 1721305516);
user_pref("toolkit.telemetry.cachedClientID", "1b564c8c-6648-48f7-bcb6-4accc70c956b");
user_pref("toolkit.telemetry.previousBuildID", "20240614163201");
